apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: label-studio-dev

namespace: label-studio-dev

resources:
  - ../../base

patchesStrategicMerge:
  - storage-patch.yaml
  - resources-patch.yaml

commonLabels:
  environment: dev