apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: label-studio-base

resources:
  - label-studio.yaml

commonLabels:
  app.kubernetes.io/name: label-studio
  app.kubernetes.io/component: annotation-platform
  app.kubernetes.io/part-of: label-studio

commonAnnotations:
  maintained-by: "DevOps Team"